import { Link } from "@tanstack/react-router";
import { ArrowRight, ChevronRight, Instagram, Menu, MessageCircle, Search, Sparkles, X } from "lucide-react";
import { useState } from "react";
import { categories, publicProducts, type PublicProduct } from "../lib/public-store";

const whatsappUrl = "https://wa.me/5511999999999?text=Ol%C3%A1%20Edition%20Geek%2C%20quero%20fazer%20uma%20encomenda";

export function PublicStore({ category, selectedProduct }: { category?: string; selectedProduct?: PublicProduct }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [query, setQuery] = useState("");
  const filtered = publicProducts.filter((item) => (!category || item.category.toLowerCase() === decodeURIComponent(category).toLowerCase()) && item.name.toLowerCase().includes(query.toLowerCase()));
  if (selectedProduct) return <StoreShell menuOpen={menuOpen} setMenuOpen={setMenuOpen}><ProductDetail product={selectedProduct} /></StoreShell>;
  return <StoreShell menuOpen={menuOpen} setMenuOpen={setMenuOpen}><StoreHero /><main className="store-main" id="catalogo"><div className="store-toolbar"><div><span className="store-kicker">CATÁLOGO EDITION GEEK</span><h2>{category ? decodeURIComponent(category) : "Peças prontas para ganhar vida"}</h2></div><label className="store-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar no catálogo..." /></label></div><div className="store-grid">{filtered.map((product) => <ProductCard key={product.id} product={product} />)}</div>{filtered.length === 0 && <div className="store-empty"><Sparkles size={30} /><h3>Nenhuma peça encontrada</h3><p>Fale com a Edition Geek para encomendar um projeto personalizado.</p><a href={whatsappUrl} target="_blank" rel="noreferrer">Fazer encomenda <ArrowRight size={15} /></a></div>}</main></StoreShell>;
}

function StoreShell({ children, menuOpen, setMenuOpen }: { children: React.ReactNode; menuOpen: boolean; setMenuOpen: (value: boolean) => void }) {
  return <div className="public-store"><header className="store-header"><Link to="/loja" className="store-logo" onClick={() => setMenuOpen(false)}><strong>EDITION</strong><b>GEEK</b><small>Impressão 3D • Produtos Geek Premium</small></Link><button className="store-menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Abrir menu">{menuOpen ? <X size={21} /> : <Menu size={21} />}</button><nav className={menuOpen ? "store-nav open" : "store-nav"}><Link to="/loja" onClick={() => setMenuOpen(false)}>Todos os Produtos</Link>{categories.slice(0, 2).map((item) => <Link key={item} to="/loja/categoria/$categoria" params={{ categoria: item }} onClick={() => setMenuOpen(false)}>{item}</Link>)}<a href={whatsappUrl} target="_blank" rel="noreferrer" onClick={() => setMenuOpen(false)}>Encomendas</a></nav><div className="store-header-actions"><a href="https://instagram.com/editiongeek" target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={18} /></a><a href={whatsappUrl} target="_blank" rel="noreferrer" aria-label="WhatsApp"><MessageCircle size={18} /></a><span className="store-badge">✦ {publicProducts.filter((item) => item.featured).length} novidades</span></div></header>{children}<StoreFooter /></div>;
}

function StoreHero() { return <section className="store-hero"><div className="store-hero-grid" /><div className="store-hero-content"><span className="store-promo-badge">✦ PRONTA ENTREGA</span><h1>Produtos Geek que saem do digital para o real</h1><p>Impressão 3D FDM e Resina • Pinturas manuais • Envio para todo o Brasil</p><div className="store-hero-actions"><a className="store-primary-button" href="#catalogo">Ver Catálogo <ChevronRight size={17} /></a><a className="store-secondary-button" href={whatsappUrl} target="_blank" rel="noreferrer">Fazer Encomenda</a></div><div className="store-stats"><div><strong>300+</strong><span>modelos</span></div><div><strong>FDM & Resina</strong><span>produção própria</span></div><div><strong>Envio imediato</strong><span>para todo Brasil</span></div></div></div></section>; }

function ProductCard({ product }: { product: PublicProduct }) { return <article className="store-product-card"><Link to="/loja/produto/$slug" params={{ slug: product.slug }} className="store-product-art" aria-label={`Ver ${product.name}`}><span>{product.type === "FDM" ? "FDM" : "RESINA"}</span><Sparkles size={31} /></Link><div className="store-product-info"><div><small>{product.category}</small><h3>{product.name}</h3></div><strong>{product.price.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</strong></div><div className="store-product-footer"><span><i /> Pronta entrega</span><Link to="/loja/produto/$slug" params={{ slug: product.slug }}>Ver peça <ArrowRight size={14} /></Link></div></article>; }

function ProductDetail({ product }: { product: PublicProduct }) { return <main className="store-detail"><Link to="/loja" className="store-back">← Voltar para o catálogo</Link><div className="store-detail-grid"><div className="store-detail-art"><Sparkles size={74} /><span>{product.type}</span></div><div className="store-detail-copy"><span className="store-kicker">{product.category}</span><h1>{product.name}</h1><p>{product.description}</p><div className="store-detail-price">{product.price.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}<small>Pronta entrega</small></div><a className="store-primary-button store-buy-button" href={`${whatsappUrl}&produto=${encodeURIComponent(product.name)}`} target="_blank" rel="noreferrer">Quero esta peça <MessageCircle size={17} /></a><div className="store-detail-note"><b>Produção Edition Geek</b><span>Peça feita com cuidado, conferida e embalada para chegar bem até você.</span></div></div></div></main>; }

function StoreFooter() { return <footer className="store-footer"><div><Link to="/loja" className="store-logo"><strong>EDITION</strong><b>GEEK</b><small>Impressão 3D • Produtos Geek Premium</small></Link><p>Objetos geek premium impressos em 3D e feitos para ocupar um lugar especial no seu universo.</p><div className="store-footer-social"><a href="https://instagram.com/editiongeek" target="_blank" rel="noreferrer"><Instagram size={16} /> Instagram</a><a href={whatsappUrl} target="_blank" rel="noreferrer"><MessageCircle size={16} /> WhatsApp</a></div></div><div><h4>Produtos</h4>{categories.map((item) => <Link key={item} to="/loja/categoria/$categoria" params={{ categoria: item }}>{item}</Link>)}</div><div><h4>Informações</h4><span>Política de encomendas</span><span>Prazos de produção</span><span>Pix • Cartão • Débito</span></div><div><h4>Contato</h4><a className="store-footer-whatsapp" href={whatsappUrl} target="_blank" rel="noreferrer"><MessageCircle size={17} /> Falar no WhatsApp</a></div><div className="store-footer-bottom">© 2025 Edition Geek • Impressão 3D & Produtos Geek • Todos os direitos reservados</div></footer>; }
