/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as LojaCategoriaCategoriaRouteImport } from './routes/loja/categoria.$categoria'
import { Route as LojaProdutoSlugRouteImport } from './routes/loja/produto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaCategoriaCategoriaRoute = LojaCategoriaCategoriaRouteImport.update({
  id: '/categoria/$categoria',
  path: '/categoria/$categoria',
  getParentRoute: () => LojaRoute,
} as any)
const LojaProdutoSlugRoute = LojaProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => LojaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loja': typeof LojaRouteWithChildren
  '/loja/categoria/$categoria': typeof LojaCategoriaCategoriaRoute
  '/loja/produto/$slug': typeof LojaProdutoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loja': typeof LojaRouteWithChildren
  '/loja/categoria/$categoria': typeof LojaCategoriaCategoriaRoute
  '/loja/produto/$slug': typeof LojaProdutoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/loja': typeof LojaRouteWithChildren
  '/loja/categoria/$categoria': typeof LojaCategoriaCategoriaRoute
  '/loja/produto/$slug': typeof LojaProdutoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/loja' | '/loja/categoria/$categoria' | '/loja/produto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/loja' | '/loja/categoria/$categoria' | '/loja/produto/$slug'
  id:
    | '__root__'
    | '/'
    | '/loja'
    | '/loja/categoria/$categoria'
    | '/loja/produto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LojaRoute: typeof LojaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/categoria/$categoria': {
      id: '/loja/categoria/$categoria'
      path: '/categoria/$categoria'
      fullPath: '/loja/categoria/$categoria'
      preLoaderRoute: typeof LojaCategoriaCategoriaRouteImport
      parentRoute: typeof LojaRoute
    }
    '/loja/produto/$slug': {
      id: '/loja/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/loja/produto/$slug'
      preLoaderRoute: typeof LojaProdutoSlugRouteImport
      parentRoute: typeof LojaRoute
    }
  }
}

interface LojaRouteChildren {
  LojaCategoriaCategoriaRoute: typeof LojaCategoriaCategoriaRoute
  LojaProdutoSlugRoute: typeof LojaProdutoSlugRoute
}

const LojaRouteChildren: LojaRouteChildren = {
  LojaCategoriaCategoriaRoute: LojaCategoriaCategoriaRoute,
  LojaProdutoSlugRoute: LojaProdutoSlugRoute,
}

const LojaRouteWithChildren = LojaRoute._addFileChildren(LojaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LojaRoute: LojaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
