// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmjxvddcqepohswpbcql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtanh2ZGRjcWVwb2hzd3BiY3FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU1Njc5NzUsImV4cCI6MjEwMTE0Mzk3NX0.8hNTPBPYg-yWWH971ceaBibf9LUAbN1a_nz6iemnmxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});